version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: character_sheet_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./character-sheet-back-end
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: character_sheet_db
      JWT_SECRET: your_key_here
    depends_on:
      - db

volumes:
  db_data:
